version: '3.8'

services:
  app:
    build: .
    ports:
      - "${SERVER_PORT}:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DOCKER_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SERVER_PORT=8080
      - JWT_SECRET=${JWT_SECRET}
      - COOKIE_SECURE=${COOKIE_SECURE}
      - COOKIE_SAME_SITE=${COOKIE_SAME_SITE}
      - APP_STORAGE_ROOT=/app/data

    volumes:
      - ${STORAGE_HOST_PATH}:/app/data

    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=soundspace
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: